spring.application.name=Books-Management-API

!DATABASE ACESS IDENTIFIERS I USED MARIADB BUT U MAY REPLACE WITH YOURS :)
spring.datasource.username=springstudent
spring.datasource.password=springstudent
spring.datasource.url=jdbc:mariadb://localhost:3306/Books


spring.security.user.name=admin
spring.security.user.password=admin
